FROM golang:1.25-alpine AS build
WORKDIR /app
COPY app/go.mod app/go.sum* ./app/
WORKDIR /app/app
RUN go mod download
COPY app/. .
RUN go build -o ../bin/service .
FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates
COPY --from=build /app/bin/service .
CMD ["./service"]